services:
  application:
    image: descubra-lugares-api:1.0
    ports:
      - "8080:8080"
    networks:
      - postgres-compose-network
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DescubraLugares
    ports:
      - "5433:5432"
    networks:
      - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge